#!/usr/bin/env php

<?php

use App\Command\DownloaderCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/../vendor/autoload.php';

$application = new Application();
$application->add(new DownloaderCommand());
$application->run();

